"""Add total_amount to CompletedJob

Revision ID: 3b48fd383b9f
Revises: 4bdb32696f71
Create Date: 2025-02-21 06:13:46.747116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b48fd383b9f'
down_revision = '4bdb32696f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('completed_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('completed_jobs', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
