"""Add can_send_photos field

Revision ID: 3f71de9475fd
Revises: 3b48fd383b9f
Create Date: 2025-02-21 16:03:02.962564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f71de9475fd'
down_revision = '3b48fd383b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_send_photos', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_jobs', schema=None) as batch_op:
        batch_op.drop_column('can_send_photos')

    # ### end Alembic commands ###
