"""add pending_type to pending_jobs

Revision ID: 4bdb32696f71
Revises: 5cd00d4b77b2
Create Date: 2025-02-20 22:51:10.849552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdb32696f71'
down_revision = '5cd00d4b77b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivered_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('pending_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('photos', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_jobs', schema=None) as batch_op:
        batch_op.drop_column('photos')
        batch_op.drop_column('pending_type')

    with op.batch_alter_table('delivered_jobs', schema=None) as batch_op:
        batch_op.drop_column('qr_code')

    # ### end Alembic commands ###
