"""add registered_by_id to completed_jobs

Revision ID: 5cd00d4b77b2
Revises: 
Create Date: 2025-02-20 03:13:10.397957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cd00d4b77b2'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Primero agregamos las columnas como nullable
    with op.batch_alter_table('completed_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('delivered_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # Actualizamos los registros existentes con el ID del admin (1)
    op.execute("UPDATE completed_jobs SET registered_by_id = 1 WHERE registered_by_id IS NULL")
    op.execute("UPDATE delivered_jobs SET registered_by_id = 1 WHERE registered_by_id IS NULL")

    # Ahora hacemos las columnas NOT NULL y agregamos las foreign keys
    with op.batch_alter_table('completed_jobs', schema=None) as batch_op:
        batch_op.alter_column('registered_by_id', nullable=False)
        batch_op.create_foreign_key(None, 'users', ['registered_by_id'], ['id'])

    with op.batch_alter_table('delivered_jobs', schema=None) as batch_op:
        batch_op.alter_column('registered_by_id', nullable=False)
        batch_op.create_foreign_key(None, 'users', ['registered_by_id'], ['id'])

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('two_factor_secret')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_secret', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('delivered_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('registered_by_id')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('completed_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('registered_by_id')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###