"""add deposit_amount to completed_jobs

Revision ID: add_deposit_amount
Create Date: 2025-02-23 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_deposit_amount'
down_revision = '5cd00d4b77b2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_jobs', schema=None) as batch_op:
        batch_op.drop_column('deposit_amount')
    # ### end Alembic commands ###
